version: '3.4'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: "no"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: homework
      MONGODB_USERNAME: mongoadmin # this is just demonstrating the app, so we can use admin just fine
      MONGODB_PASSWORD: mongopass
      MONGODB_HOSTNAME: mongodb
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: "no"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    networks:
      - backend


networks:
  backend:
    driver: bridge